spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbootbase?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=UTC
    username: root
    password: S@feinis12345678

  jpa:
    hibernate:
      ddl-auto: update  # 第一次简表create  后面用update
    show-sql: true